//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vi2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DishAndDrink
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DishAndDrink()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Composition { get; set; }
        public string Foto { get; set; }
        public decimal Price { get; set; }
        public Nullable<int> IdCategoryDish { get; set; }
        public Nullable<int> IdCategoryDrink { get; set; }
        public Nullable<int> IdCategoryDishAndDrink { get; set; }
        public Nullable<int> IdUser { get; set; }
    
        public virtual CategoryDish CategoryDish { get; set; }
        public virtual CategoryDishAndDrink CategoryDishAndDrink { get; set; }
        public virtual CategoryDrink CategoryDrink { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
    }
}
