//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vi2.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RestaurantBDEntities1 : DbContext
    {
        private static RestaurantBDEntities1 _context;
        public static RestaurantBDEntities1 GetContext()
        {
            if (_context == null)
                _context = new RestaurantBDEntities1();
            return _context;
        }
        public RestaurantBDEntities1()
            : base("name=RestaurantBDEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CategoryDish> CategoryDish { get; set; }
        public virtual DbSet<CategoryDishAndDrink> CategoryDishAndDrink { get; set; }
        public virtual DbSet<CategoryDrink> CategoryDrink { get; set; }
        public virtual DbSet<DishAndDrink> DishAndDrink { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
